name: another_stepper
description: Vertical and Horizontal steppers with title and subtitle and custom styles.
version: 1.0.0
repository: https://github.com/BlackNoir1/another_stepper

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: