name: another_stepper
description: A new Flutter project.
version: 0.0.1
repository: https://github.com/BlackNoir1/another_stepper

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: